rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-19mode

notifications:
  irc: "irc.freenode.org#celluloid"

services:
  - redis-server
