language: ruby
bundler_args: --jobs=3 --retry=3
cache: bundler
sudo: false

services:
  - redis-server

rvm:
  - 2.0.0
  - 2.1.4
  - 2.2.2
  - ruby-head
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2

notifications:
  irc: "irc.freenode.org#celluloid"
